name: CI
on: push
env:
  SERVER_ADDR: ${{ secrets.SERVER_ADDR }}

jobs:
  build-web:
    name: Build (Web)
    runs-on: ubuntu-latest
    env:
      WSS: wss
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown

      - name: Install cargo-geng
        run: |
          cargo install cargo-geng --git https://github.com/geng-engine/cargo-geng
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: geng
          args: build --release --platform web

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: target/geng

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build-web
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Deploy GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web
      - name: Upload itch.io (Web)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: monke-pizza
          ITCH_USER: kuviman
          PACKAGE: web
      - name: Deploy server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: systemctl --user restart monke-pizza
